Remove obsolete e-smith fail2ban database
NethServer/nethserver-fail2ban pull request #109
Opened 2020-12-16 16:00 UTC by stephdl

2020-12-16 16:17 UTC, gsanchietti requested changes
Since we already have a cleanup action named `nethserver-fail2ban-clean-sqlite-backup`, let's try to put everything in one place:
- rename `nethserver-fail2ban-clean-sqlite-backup` to something like ``nethserver-fail2ban-cleanup`
- move the code from `nethserver-fail2ban-remove-obsolete-esmith-F2B-database ` to the above action

2020-12-16 16:17 UTC, gsanchietti commented on createlinks
> +             'nethserver-fail2ban-remove-obsolete-esmith-F2B-database' => '20');
Again? :(
Please, do not use upper cases in action names.

Argh, I didn't catch `nethserver-fail2ban-cleanShorewallDynamic` before :/

2020-12-16 16:17 UTC, gsanchietti commented on root/etc/e-smith/events/actions/nethserver-fail2ban-remove-obsolete-esmith-F2B-database
> +# this database is saved inside my.nethesis.it with a subscription
This is true also for subscription:
```
```suggestion
# The old esmith fail2ban database is not used anymore,
# just remove it to not send to subscription server with inventory
```

2020-12-16 17:24 UTC, stephdl commented on createlinks
> +             'nethserver-fail2ban-remove-obsolete-esmith-F2B-database' => '20');
done

2020-12-16 17:24 UTC, stephdl commented on root/etc/e-smith/events/actions/nethserver-fail2ban-remove-obsolete-esmith-F2B-database
> +# this database is saved inside my.nethesis.it with a subscription
done

2020-12-17 07:12 UTC, gsanchietti approved these changes

2020-12-17 17:21 UTC, merged