Perpetual recidive replaced by Incremental recidive
NethServer/nethserver-fail2ban pull request #95
Opened 2020-09-08 14:44 UTC by stephdl

2020-09-11 10:01 UTC, gsanchietti commented on root/etc/e-smith/db/configuration/defaults/fail2ban/BanTime_Incremental
> +false
Why the old prop had a status value (enabled/disabled) and now it's true/false?

2020-09-11 12:03 UTC, gsanchietti commented on ui/public/i18n/language.json
> +        "BanTime_Incremental": "The incremental ban time allows to increase the time of ban by a multiplier (2,4,6,8,10,20,30,60,300,720,1440,2880) after each faillure found in log. It allows you to
```suggestion
        "BanTime_Incremental": "The incremental ban time allows to increase the time of ban after each failure found in log. It allows you to set a shorter ban time, a valid user can be banned for a short time but a brute force attacker will be banned for a long time. The recidive jail is disabled by the Incremental BanTime"
```

You say that `The recidive jail is disabled by the Incremental BanTime`, but I can't find recidive configuration inside the UI

2020-09-11 12:05 UTC, gsanchietti reviewed
I also have a question: do you think that it could be useful to enable the incremental ban time on machines where perpetual recidive was enabled?

2020-09-11 13:18 UTC, stephdl commented on root/etc/e-smith/db/configuration/defaults/fail2ban/BanTime_Incremental
> +false
Simple because the `bantime.incremental` takes as settings `true/false` like any jail. A jail in our settings uses also `true/false`

2020-09-11 13:28 UTC, stephdl commented
>You say that The recidive jail is disabled by the Incremental BanTime, but I can't find recidive configuration inside the UI 

If you check the jail recidive, when you enable/disable the incremental ban, then you enable disable the recidive. Moreover when you enable the incremental ban, then the jail recidive is disabled by vueJS

2020-09-11 13:29 UTC, stephdl commented
> I also have a question: do you think that it could be useful to enable the incremental ban time on machines where perpetual recidive was enabled?

I would say no, because the maximum ban time of incremental ban is the same than recidive (2 weeks maximum)

2020-09-14 10:00 UTC, gsanchietti requested changes
The radio button should have 3 states:
- incremental ban time
- static ban time
- disabled: if both `BanTime_Incremental` and `Recidive_status` are disabled

2020-09-14 16:49 UTC, stephdl commented
obsoleted by https://github.com/NethServer/nethserver-fail2ban/pull/96

2020-09-14 16:49 UTC, closed without merging